"""
Reports Routes
GET  /api/reports         - List all reports
POST /api/reports/pdf     - Generate PDF report
POST /api/reports/csv     - Generate CSV export
GET  /api/reports/<id>/download - Download a report
"""
import os
import csv
import io
from datetime import datetime
from flask import Blueprint, request, jsonify, send_file, current_app
from database.db import get_db
from utils.jwt_helper import token_required

reports_bp = Blueprint('reports', __name__)

@reports_bp.route('', methods=['GET'])
@token_required
def get_reports():
    """List all generated reports."""
    db = get_db()
    reports = db.execute(
        "SELECT * FROM reports ORDER BY created_at DESC"
    ).fetchall()
    return jsonify([dict(r) for r in reports])

@reports_bp.route('/pdf', methods=['POST'])
@token_required
def generate_pdf():
    """Generate a PDF incident/threat report using ReportLab."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch, cm
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        from reportlab.platypus import KeepTogether
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
    except ImportError:
        return jsonify({'error': 'ReportLab not installed. Run: pip install reportlab'}), 500

    data = request.get_json() or {}
    report_type = data.get('type', 'threat_summary')
    alert_ids = data.get('alert_ids', [])

    db = get_db()

    # Fetch alerts
    if alert_ids:
        placeholders = ','.join('?' * len(alert_ids))
        alerts = db.execute(
            f"SELECT * FROM alerts WHERE id IN ({placeholders}) ORDER BY created_at DESC", alert_ids
        ).fetchall()
    else:
        alerts = db.execute(
            "SELECT * FROM alerts ORDER BY created_at DESC LIMIT 50"
        ).fetchall()
    alerts = [dict(a) for a in alerts]

    # Create PDF
    reports_folder = current_app.config['REPORTS_FOLDER']
    os.makedirs(reports_folder, exist_ok=True)
    timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
    filename = f'sentinelx_report_{timestamp}.pdf'
    filepath = os.path.join(reports_folder, filename)

    doc = SimpleDocTemplate(filepath, pagesize=A4,
                            leftMargin=1.5*cm, rightMargin=1.5*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle('Title', parent=styles['Heading1'],
                                  fontSize=22, textColor=colors.HexColor('#06b6d4'),
                                  spaceAfter=6, alignment=TA_CENTER)
    subtitle_style = ParagraphStyle('Subtitle', parent=styles['Normal'],
                                     fontSize=11, textColor=colors.HexColor('#64748b'),
                                     alignment=TA_CENTER, spaceAfter=20)
    section_style = ParagraphStyle('Section', parent=styles['Heading2'],
                                    fontSize=14, textColor=colors.HexColor('#1e293b'),
                                    spaceBefore=16, spaceAfter=8,
                                    borderPad=4)
    body_style = ParagraphStyle('Body', parent=styles['Normal'],
                                 fontSize=9, textColor=colors.HexColor('#374151'),
                                 leading=14)

    SEVERITY_COLORS = {
        'critical': colors.HexColor('#ef4444'),
        'high': colors.HexColor('#f97316'),
        'medium': colors.HexColor('#eab308'),
        'low': colors.HexColor('#22c55e'),
    }

    elements = []

    # Header
    elements.append(Paragraph('SENTINELX', title_style))
    elements.append(Paragraph('Enterprise Threat Detection & Incident Response Platform', subtitle_style))
    elements.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#06b6d4')))
    elements.append(Spacer(1, 12))

    # Report metadata
    meta_data = [
        ['Report Type:', report_type.replace('_', ' ').title()],
        ['Generated:', datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')],
        ['Generated By:', request.current_user.get('username', 'system')],
        ['Total Alerts:', str(len(alerts))],
    ]
    meta_table = Table(meta_data, colWidths=[3*cm, 12*cm])
    meta_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#06b6d4')),
        ('TEXTCOLOR', (1, 0), (1, -1), colors.HexColor('#1e293b')),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.HexColor('#f8fafc'), colors.white]),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 20))

    # Summary statistics
    if alerts:
        elements.append(Paragraph('Executive Summary', section_style))

        severity_counts = {'critical': 0, 'high': 0, 'medium': 0, 'low': 0}
        for a in alerts:
            sev = a.get('severity', 'low').lower()
            if sev in severity_counts:
                severity_counts[sev] += 1

        avg_risk = sum(a.get('risk_score', 0) for a in alerts) / len(alerts) if alerts else 0

        summary_data = [
            ['Metric', 'Count'],
            ['Critical Alerts', str(severity_counts['critical'])],
            ['High Alerts', str(severity_counts['high'])],
            ['Medium Alerts', str(severity_counts['medium'])],
            ['Low Alerts', str(severity_counts['low'])],
            ['Average Risk Score', f'{avg_risk:.1f}/100'],
        ]
        summary_table = Table(summary_data, colWidths=[8*cm, 7*cm])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e293b')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#f1f5f9'), colors.white]),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        elements.append(summary_table)
        elements.append(Spacer(1, 20))

        # Alerts detail
        elements.append(Paragraph('Alert Details', section_style))
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e2e8f0')))
        elements.append(Spacer(1, 8))

        # Table header
        alert_headers = ['ID', 'Alert Name', 'Severity', 'Risk', 'Source IP', 'MITRE', 'Status']
        alert_table_data = [alert_headers]
        for a in alerts[:30]:  # Limit to 30 in detail
            alert_table_data.append([
                str(a.get('id', '')),
                a.get('alert_name', '')[:30],
                a.get('severity', '').upper(),
                str(a.get('risk_score', '')),
                a.get('source_ip', ''),
                a.get('mitre_technique', ''),
                a.get('status', '').upper(),
            ])

        col_widths = [1.2*cm, 5.5*cm, 2.2*cm, 1.5*cm, 3*cm, 2.2*cm, 2.5*cm]
        alerts_table = Table(alert_table_data, colWidths=col_widths, repeatRows=1)
        alerts_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f172a')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#f8fafc'), colors.white]),
            ('GRID', (0, 0), (-1, -1), 0.3, colors.HexColor('#e2e8f0')),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(alerts_table)

        # Color severity cells
        for row_idx, a in enumerate(alerts[:30], start=1):
            sev = a.get('severity', 'low').lower()
            color = SEVERITY_COLORS.get(sev, colors.gray)
            alerts_table.setStyle(TableStyle([
                ('TEXTCOLOR', (2, row_idx), (2, row_idx), color),
                ('FONTNAME', (2, row_idx), (2, row_idx), 'Helvetica-Bold'),
            ]))

        elements.append(Spacer(1, 20))

        # Recommendations section
        elements.append(Paragraph('Key Recommendations', section_style))
        rec_style = ParagraphStyle('Rec', parent=body_style, leftIndent=10, spaceAfter=4)
        seen_types = set()
        for a in alerts:
            threat_type = a.get('threat_type', '')
            if threat_type and threat_type not in seen_types:
                seen_types.add(threat_type)
                rec_text = a.get('recommendation', '')
                if rec_text:
                    elements.append(Paragraph(f'<b>• {a.get("alert_name", threat_type)}:</b>', body_style))
                    for line in rec_text.split('\n')[:4]:
                        if line.strip().startswith('•'):
                            elements.append(Paragraph(f'  {line.strip()}', rec_style))
                    elements.append(Spacer(1, 4))

    # Footer
    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e2e8f0')))
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'],
                                   fontSize=8, textColor=colors.HexColor('#94a3b8'),
                                   alignment=TA_CENTER)
    elements.append(Paragraph(
        'SentinelX — Enterprise Threat Detection & Incident Response Platform | CONFIDENTIAL',
        footer_style
    ))

    doc.build(elements)

    # Save report record to DB
    db.execute("""
        INSERT INTO reports (report_name, report_type, file_path, generated_by)
        VALUES (?, ?, ?, ?)
    """, (filename, 'pdf', filepath, request.current_user.get('username', 'system')))
    db.commit()

    return send_file(filepath, as_attachment=True, download_name=filename,
                     mimetype='application/pdf')

@reports_bp.route('/csv', methods=['POST'])
@token_required
def generate_csv():
    """Generate a CSV export of alerts."""
    data = request.get_json() or {}
    alert_ids = data.get('alert_ids', [])

    db = get_db()

    if alert_ids:
        placeholders = ','.join('?' * len(alert_ids))
        alerts = db.execute(
            f"SELECT * FROM alerts WHERE id IN ({placeholders}) ORDER BY created_at DESC", alert_ids
        ).fetchall()
    else:
        alerts = db.execute(
            "SELECT * FROM alerts ORDER BY created_at DESC"
        ).fetchall()
    alerts = [dict(a) for a in alerts]

    # Build CSV in memory
    output = io.StringIO()
    if alerts:
        fieldnames = list(alerts[0].keys())
        writer = csv.DictWriter(output, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(alerts)

    csv_content = output.getvalue().encode('utf-8')

    # Save report record
    timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
    filename = f'sentinelx_alerts_{timestamp}.csv'
    reports_folder = current_app.config['REPORTS_FOLDER']
    os.makedirs(reports_folder, exist_ok=True)
    filepath = os.path.join(reports_folder, filename)
    with open(filepath, 'wb') as f:
        f.write(csv_content)

    db.execute("""
        INSERT INTO reports (report_name, report_type, file_path, generated_by)
        VALUES (?, ?, ?, ?)
    """, (filename, 'csv', filepath, request.current_user.get('username', 'system')))
    db.commit()

    return send_file(
        io.BytesIO(csv_content),
        as_attachment=True,
        download_name=filename,
        mimetype='text/csv'
    )
